name: docker-build-push

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
env:
  file: ./Dockerfile
  tags: bruce6x/test:latest
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        file: ${{ env.file }}
        tags: ${{ env.tags }}

    - name: Run Docker container
      run: |
        docker run --name test-container ${{ env.tags }}
