# https://github.com/marketplace/actions/super-linter
name: super-linter
on:
  workflow_dispatch:
jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
